# Generated by Django 5.1.6 on 2025-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_finale', '0002_vehicle_remove_profile_user_loyaltyprogram_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'tbl_location',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(max_length=20),
        ),
    ]
