# Generated by Django 5.1.6 on 2025-02-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_finale', '0005_remove_booking_location_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='the_finale.post'),
        ),
    ]
